version: '3'

services:
  pg:
    image: postgres:12.2
    #    volumes:
    #      - ./docker/postgres/docker-entrypoint-initdb.d/init.sql:/docker-entrypoint-initdb.d/init.sql
    volumes:
      - ./datastore/pg:/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: 'example'
      POSTGRES_USER: 'postgres'
      POSTGRES_DB: 'develop'
      PGDATA: /var/lib/postgresql/data/pgdata

  pgadmin:
    image: dpage/pgadmin4:6
    ports:
      - 3081:80
    depends_on:
      - pg
    environment:
      PGADMIN_DEFAULT_PASSWORD: 'example'
      PGADMIN_DEFAULT_EMAIL: 'al.shreyner@gmail.com'

  mongo:
    image: mongo:5
    ports:
      - 27017:27017
    volumes:
      - ./datastore/mongo:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: 'root'
      MONGO_INITDB_ROOT_PASSWORD: 'example'
      MONGO_INITDB_DATABASE: 'main'

  mongo-express:
    image: mongo-express
    ports:
      - 3084:8081
    restart: unless-stopped
    depends_on:
      - mongo
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: 'root'
      ME_CONFIG_MONGODB_ADMINPASSWORD: 'example'

  redis:
    image: library/redis:6.2
    ports:
      - 6379:6379

  redis-commander:
    image: rediscommander/redis-commander:latest
    depends_on:
      - redis
    environment:
      - REDIS_HOSTS=redis:redis
    ports:
      - 3082:8081

  main-nats:
    image: library/nats-streaming:0.21.1
    depends_on:
      - pg
    ports:
      - 4222:4222
      - 3083:8222
    command: -SDV -p 4222 -m 8222 --store sql --sql_driver postgres --sql_source="user=postgres password=example host=172.17.0.1 database=nats sslmode=disable"
